COMPILE :=source/ping.c  
COMPILE +=source/net_init.cxx 
COMPILE +=source/tcp_server.c
COMPILE +=source/tcp_client.c

COMPILE +=source/udp_recv.c
COMPILE +=source/udp_send.c

COMPILE +=source/show_network_table.c

COMPILE +=source/ifconfig.c

COMPILE +=source/connecthostport.c
COMPILE +=source/igd_desc_parse.c
COMPILE +=source/minisoap.c
COMPILE +=source/minissdpc.c
COMPILE +=source/miniupnpc.c
COMPILE +=source/miniwget.c
COMPILE +=source/minixml.c
COMPILE +=source/upnperrors.c
COMPILE +=source/upnpcommands.c
COMPILE +=source/upnpreplyparse.c
COMPILE +=source/upnp.c

#COMPILE +=source/cpuload.c

include ../../config.mk
include ../../rules.mk

pre-build:
pre-clean:

