COMPILE := source/dump.c
COMPILE += source/kill.c
COMPILE += source/thread_info.c
COMPILE += source/set_thread_priority.c
COMPILE += source/dhry.c

include ../../config.mk
include ../../rules.mk

pre-build:
pre-clean:

