#ifndef CYGONCE_PKGCONF_FS_JFFS2_H
#define CYGONCE_PKGCONF_FS_JFFS2_H
/*
 * File <pkgconf/fs_jffs2.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

//#define CYGOPT_FS_JFFS2_GCTHREAD 1
//#define CYGNUM_JFFS2_GC_THREAD_PRIORITY 30
//#define CYGNUM_JFFS2_GC_THREAD_PRIORITY_30
//#define CYGNUM_JFFS2_GC_THREAD_STACK_SIZE 8192
//#define CYGNUM_JFFS2_GC_THREAD_STACK_SIZE_8192

#define CYGNUM_JFFS2_GS_THREAD_TICKS 100
#define CYGNUM_JFFS2_GS_THREAD_TICKS_100
#define CYGOPT_FS_JFFS2_WRITE 1
#define CYGOPT_FS_JFFS2_DEBUG 0
#define CYGOPT_FS_JFFS2_DEBUG_0
#define CONFIG_JFFS2_FS_DEBUG 0
#define CONFIG_JFFS2_FS_DEBUG_0
//#define CONFIG_JFFS2_FS_DEBUG 2
//#define CONFIG_JFFS2_FS_DEBUG_2

//#define CYGOPT_FS_JFFS2_COMPRESS 1
//#define JFFS2_COMPRESSION 1
//#define CYGOPT_FS_JFFS2_COMPRESS_ZLIB 1
//#define CONFIG_JFFS2_ZLIB 1
//#define CYGOPT_FS_JFFS2_COMPRESS_RTIME 1
//#define CONFIG_JFFS2_RTIME 1
#define CYGOPT_FS_JFFS2_COMPRESS_CMODE NONE
#define CYGOPT_FS_JFFS2_COMPRESS_CMODE_NONE
#define CONFIG_JFFS2_CMODE NONE
#define CONFIG_JFFS2_CMODE_NONE

#define CYGNUM_FS_JFFS2_RAW_NODE_REF_CACHE_POOL_SIZE 0
#define CYGNUM_FS_JFFS2_RAW_NODE_REF_CACHE_POOL_SIZE_0

#define CYGPKG_IO_FLASH_BLOCK_DEVICE 1
#define CYGINT_ISO_FCNTL 1

#endif

