COMPILE := source/how_to_add_command.c
COMPILE += source/how_to_use_init_func.c
COMPILE += source/how_to_create_thread.c
COMPILE += source/how_to_print.c
COMPILE += source/create_hello_threads.c

include ../../config.mk
include ../../rules.mk

pre-build:
pre-clean:

